### ISSUE TITLE
Add nix shell banner

### ISSUE THREAD

**Issue by srid** [srid/haskell-template#18]
Entering `nix develop` should print a welcome message similar to how https://github.com/yusdacra/rust-nix-templater does

<img width="646" alt="image" src="https://user-images.githubusercontent.com/3998/167217165-43e46c15-d22a-4fe5-8afa-b458775f19c4.png">

**Comment by srid** [comment]
If we can do this in a general way (abstracted way as an external repo to be used as a flake input, with minimal Nix stub) that would be ideal. cc @yusdacra

**Comment by yusdacra** [comment]
The devshell message there comes from https://github.com/numtide/devshell, which is a lightweight devshell with nice features. `haskellPackages` would need to use that for a devshell message. But `haskell-template` could probably just use `devshell` and set up a shellHook that sources the `haskellPackages` shell and add a commands using `devshell` configuration.

**Comment by srid** [comment]
Done in https://github.com/srid/haskell-template/pull/72
