### ISSUE TITLE
Unable to use HLS with VSCode on Mac os

### ISSUE THREAD

**Issue by aammfe** [srid/haskell-template#24]
OS - MAC OS Monterey (M1)
Nix - nix (Nix) 2.9.1

steps to reproduce:
1- clone repo
2- run: nix develop -c haskell-language-server
OUTPUT : 
Completed (1 file worked, 0 files failed)

Got an HLS error on VS Code
<img width="1685" alt="image" src="https://user-images.githubusercontent.com/11896817/176215206-edbc45a7-1b6d-4ed4-a919-b5c0d6d7d56f.png">

**Comment by srid** [comment]
@aammfe Did you follow the 'First-time setup' instructions [here](https://github.com/srid/haskell-template#getting-started), in particular the "Nix-Env: Select Environment" part? 

Your screenshot doesn't show me the VSCode footer bar.

**Comment by aammfe** [comment]
yes, previously I had selected the shell.nix
after uninstalling HLS globally and setting **Haskell: Manage HLS = Path** instead of ghcup finally it started working.

**Comment by srid** [comment]
Oh great; added this config to the workspace: https://github.com/srid/haskell-template/commit/7c21b229725e340700a736c5accf053b6258af66
