### ISSUE TITLE
Add Githook for Code Formatting

### ISSUE THREAD

**Issue by EvanPiro** [srid/haskell-template#33]
Putting auto-formatting on a per commit basis would save the developer time resolving formatting issues due to failing CI.

Getting something like the following in a githook would suffice:
 `nix develop -c "treefmt"`

**Comment by srid** [comment]
I wouldn't enable it by default, but we can add documentation (linked from README.md) explaining to the user how to do it ... possibly based on:

- https://github.com/cachix/pre-commit-hooks.nix
- https://github.com/hercules-ci/pre-commit-hooks.nix/blob/flakeModule/flake-module.nix

**Comment by srid** [comment]
Relevant: #36 (a nix check to make sure that source code was autoformatted).

**Comment by srid** [comment]
Relevant: https://github.com/numtide/treefmt/issues/78

**Comment by srid** [comment]
https://github.com/srid/haskell-flake/issues/136

**Comment by srid** [comment]
Closing in favour of https://github.com/srid/haskell-flake/issues/136
