### ISSUE TITLE
Implement this repo as an actual Nix template

### ISSUE THREAD

**Issue by HariAmoor-professional** [srid/haskell-template#63]
The ideal interface for a Nix-based scaffold is `nix flake init -t github:$OWNER/$REPO`. In other words, it's generally a better practice to use [Nix templates](https://github.com/nixos/templates) with this stuff, IIUC.

Can we go in that direction for this repo?

@srid Would appreciate your thoughts

**Comment by srid** [comment]
I agree totally as long as it can be done without much fanfare. What will it take?

**Comment by HariAmoor-professional** [comment]
It's not a lot of fanfare; really just a lot of copy/paste. We just have to do something like this.

```
...
outputs = {self, ...}: {
  ...
  templates.default = {
    path = ./.;
    description = "Easy template for generic Haskell projects"
    welcomeText= ''
      Welcome to your new Haskell project!

      This template is used, among other places, by Platonic Systems internally and for its clients.

      Please use Github Issues or contact the lead developer, Sridhar Ratnakumar, at [a-zA-Z0-9]*@srid.ca for any bug reports or feature requests.
    '';
  };
};
```

In fact, I think this whole repo can be implemented as the default template of haskell-flake, which would simplify development since we wouldn't have to make changes to two repos every time we want to update this stuff. This is a bit of a radical change, however, so it needn't be done immediately in order to take advantage of templates.

**Comment by HariAmoor-professional** [comment]
See the [template given by the CTL repo](https://github.com/Plutonomicon/cardano-transaction-lib/tree/develop/templates/ctl-scaffold) defined as `templates.default` in the root flake as an example.

**Comment by srid** [comment]
> I think this whole repo can be implemented as the default template of haskell-flake,

Let's think about this a bit first. It probably should be done as part of https://github.com/srid/haskell-flake/issues/25

**Comment by srid** [comment]
Closing in favour of https://github.com/srid/haskell-flake/issues/25#issuecomment-1357759942
